language: node_js

sudo: false

git:
  depth: 3

node_js:
  - '0.10'
  - 0.12
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13

script:
  - npm run-script cover

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
